server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Le dice que no se registre a sí mismo
    fetch-registry: false        # Le dice que no intente descargar rutas de otros Eurekas